<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Pub/Sub messaging, event handler, and topic abstractions for Centra.</Description>
    <RootNamespace>Centra.PubSub</RootNamespace>
    <PackageTags>$(PackageTags);pubsub;messaging;topics;events;handlers</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Centra.Events.Abstractions\Centra.Events.Abstractions.csproj" />
  </ItemGroup>
</Project>
