<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Distributed lock provider implementation for Centra.</Description>
    <RootNamespace>Centra.Locks</RootNamespace>
    <PackageTags>$(PackageTags);locks;distributed-lock;mutex;leases</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Centra.Locks.Abstractions\Centra.Locks.Abstractions.csproj" />
    <ProjectReference Include="..\Centra.Runtime\Centra.Runtime.csproj" />
  </ItemGroup>
</Project>
