<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Description>RabbitMQ event consumer service that processes incoming orders and uses Centra Service Invocation to call the API service.</Description>
    <RootNamespace>Centra.Sample.RabbitSimulation.Consumer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Centra.Hosting\Centra.Hosting.csproj" />
    <ProjectReference Include="..\..\..\src\Centra.Providers.RabbitMQ\Centra.Providers.RabbitMQ.csproj" />
    <ProjectReference Include="..\Contracts\Centra.Sample.RabbitSimulation.Contracts.csproj" />
  </ItemGroup>

</Project>
