<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Input and output binding trigger abstractions for Centra.</Description>
    <RootNamespace>Centra.Bindings</RootNamespace>
    <PackageTags>$(PackageTags);bindings;triggers;cron;webhooks</PackageTags>
  </PropertyGroup>
</Project>
