<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Description>API Service for Centra Flotilla simulation demonstrating Service Invocation targets.</Description>
    <RootNamespace>Centra.Sample.FlotillaSimulation.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Centra.Sample.FlotillaSimulation.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>

</Project>
