using System.Linq;
using System.Text;

namespace Centra.Generators;

internal static class ActorClientSourceEmitter
{
    public static string Emit(ActorClientModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Centra.Generators\", \"1.0.0.0\")]");
        sb.AppendLine($"public sealed class {model.ProxyClassName} : {model.InterfaceName}, global::Centra.Actors.IActorProxy");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Centra.Actors.ActorIdentity _identity;");
        sb.AppendLine("    private readonly global::Centra.Actors.ActorManager _actorManager;");
        sb.AppendLine("    private readonly global::Centra.Actors.IActorPlacementDirector _placementDirector;");
        sb.AppendLine("    private readonly global::Centra.Invocation.IServiceInvoker? _serviceInvoker;");
        sb.AppendLine();
        sb.AppendLine("    public global::Centra.Actors.ActorIdentity Identity => _identity;");
        sb.AppendLine();
        sb.AppendLine($"    public {model.ProxyClassName}(");
        sb.AppendLine("        global::Centra.Actors.ActorIdentity identity,");
        sb.AppendLine("        global::Centra.Actors.ActorManager actorManager,");
        sb.AppendLine("        global::Centra.Actors.IActorPlacementDirector placementDirector,");
        sb.AppendLine("        global::Centra.Invocation.IServiceInvoker? serviceInvoker = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        _identity = identity;");
        sb.AppendLine("        _actorManager = actorManager ?? throw new global::System.ArgumentNullException(nameof(actorManager));");
        sb.AppendLine("        _placementDirector = placementDirector ?? throw new global::System.ArgumentNullException(nameof(placementDirector));");
        sb.AppendLine("        _serviceInvoker = serviceInvoker;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {model.InterfaceName} Create(");
        sb.AppendLine("        global::Centra.Actors.ActorId actorId,");
        sb.AppendLine("        global::Centra.Actors.ActorManager actorManager,");
        sb.AppendLine("        global::Centra.Actors.IActorPlacementDirector placementDirector,");
        sb.AppendLine("        global::Centra.Invocation.IServiceInvoker? serviceInvoker = null,");
        sb.AppendLine("        global::Centra.Actors.ActorType? actorType = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var type = actorType ?? new global::Centra.Actors.ActorType(\"{model.ActorTypeName}\");");
        sb.AppendLine("        var identity = new global::Centra.Actors.ActorIdentity(type, actorId);");
        sb.AppendLine($"        return new {model.ProxyClassName}(identity, actorManager, placementDirector, serviceInvoker);");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in model.Methods)
        {
            var paramList = new StringBuilder();
            var argList = new StringBuilder();
            var nonCtParams = method.Parameters.Where(p => !p.IsCancellationToken).ToArray();

            for (var i = 0; i < method.Parameters.Count; i++)
            {
                if (i > 0)
                {
                    paramList.Append(", ");
                    argList.Append(", ");
                }
                var p = method.Parameters[i];
                paramList.Append($"{p.Type} {p.Name}");
                if (p.IsCancellationToken)
                {
                    paramList.Append(" = default");
                }
                argList.Append(p.Name);
            }

            var ctVar = method.CancellationTokenParameter != null
                ? method.CancellationTokenParameter.Name
                : "global::System.Threading.CancellationToken.None";

            sb.AppendLine($"    public async {method.ReturnType} {method.MethodName}({paramList})");
            sb.AppendLine("    {");
            sb.AppendLine($"        using var activity = global::Centra.Diagnostics.CentraDiagnostics.StartActorInvokeActivity(_identity.Type.Value, _identity.Id.Value, \"{method.MethodName}\");");
            sb.AppendLine();
            sb.AppendLine("        if (_placementDirector.IsLocal(_identity))");
            sb.AppendLine("        {");

            if (method.GenericReturnType != null)
            {
                sb.AppendLine("            return await _actorManager.DispatchAsync(_identity, async actor =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                return await (({model.InterfaceName})actor).{method.MethodName}({argList}).ConfigureAwait(false);");
                sb.AppendLine($"            }}, {ctVar}).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine("            await _actorManager.DispatchAsync(_identity, async actor =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                await (({model.InterfaceName})actor).{method.MethodName}({argList}).ConfigureAwait(false);");
                sb.AppendLine($"            }}, {ctVar}).ConfigureAwait(false);");
                sb.AppendLine("            return;");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        if (_serviceInvoker == null)");
            sb.AppendLine("        {");
            sb.AppendLine("            throw new global::System.InvalidOperationException($\"Cannot invoke remote actor '{_identity}' because no IServiceInvoker was configured.\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        var targetNode = _placementDirector.ResolveNodeId(_identity);");
            sb.AppendLine("        var path = $\"centra/actors/{_identity.Type.Value}/{_identity.Id.Value}/method/" + method.MethodName + "\";");

            string reqType;
            string payload;

            if (nonCtParams.Length == 0)
            {
                reqType = "object?";
                payload = "null";
            }
            else if (nonCtParams.Length == 1)
            {
                reqType = nonCtParams[0].Type;
                payload = nonCtParams[0].Name;
            }
            else
            {
                reqType = "object";
                payload = "new { " + string.Join(", ", nonCtParams.Select(p => p.Name)) + " }";
            }

            if (method.GenericReturnType != null)
            {
                sb.AppendLine($"        return await _serviceInvoker.InvokeMethodAsync<{reqType}, {method.GenericReturnType}>(");
                sb.AppendLine("            targetNode,");
                sb.AppendLine("            path,");
                sb.AppendLine($"            {payload},");
                sb.AppendLine("            \"POST\",");
                sb.AppendLine("            null,");
                sb.AppendLine($"            {ctVar}).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"        await _serviceInvoker.InvokeMethodAsync<{reqType}, object?>(");
                sb.AppendLine("            targetNode,");
                sb.AppendLine("            path,");
                sb.AppendLine($"            {payload},");
                sb.AppendLine("            \"POST\",");
                sb.AppendLine("            null,");
                sb.AppendLine($"            {ctVar}).ConfigureAwait(false);");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
