using System.Text;

namespace Centra.Generators;

internal static class ServiceClientSourceEmitter
{
    public static string Emit(ServiceClientModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Centra.Generators\", \"1.0.0.0\")]");
        sb.AppendLine($"public sealed class {model.ProxyClassName} : {model.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Centra.Invocation.IServiceInvoker _invoker;");
        sb.AppendLine("    private readonly string _appId;");
        sb.AppendLine();
        sb.AppendLine($"    public {model.ProxyClassName}(global::Centra.Invocation.IServiceInvoker invoker, string? appId = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        _invoker = invoker ?? throw new global::System.ArgumentNullException(nameof(invoker));");
        sb.AppendLine($"        _appId = appId ?? \"{model.AppId}\";");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {model.InterfaceName} Create(global::Centra.Invocation.IServiceInvoker invoker, string? appId = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.ProxyClassName}(invoker, appId);");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in model.Methods)
        {
            var paramList = new StringBuilder();
            for (var i = 0; i < method.Parameters.Count; i++)
            {
                if (i > 0) paramList.Append(", ");
                var p = method.Parameters[i];
                paramList.Append($"{p.Type} {p.Name}");
                if (p.IsCancellationToken)
                {
                    paramList.Append(" = default");
                }
            }

            var ctVar = method.CancellationTokenParameter != null
                ? method.CancellationTokenParameter.Name
                : "global::System.Threading.CancellationToken.None";

            var reqType = method.BodyParameter != null ? method.BodyParameter.Type : "object?";
            var reqArg = method.BodyParameter != null ? method.BodyParameter.Name : "null";

            sb.AppendLine($"    public async {method.ReturnType} {method.MethodName}({paramList})");
            sb.AppendLine("    {");

            if (method.GenericReturnType != null)
            {
                sb.AppendLine($"        var response = await _invoker.InvokeMethodAsync<{reqType}, {method.GenericReturnType}>(");
                sb.AppendLine($"            _appId,");
                sb.AppendLine($"            \"{method.TargetMethodName}\",");
                sb.AppendLine($"            {reqArg},");
                sb.AppendLine($"            \"{method.HttpVerb}\",");
                sb.AppendLine("            null,");
                sb.AppendLine($"            {ctVar}).ConfigureAwait(false);");
                sb.AppendLine("        return response;");
            }
            else
            {
                sb.AppendLine($"        await _invoker.InvokeMethodAsync<{reqType}, object?>(");
                sb.AppendLine($"            _appId,");
                sb.AppendLine($"            \"{method.TargetMethodName}\",");
                sb.AppendLine($"            {reqArg},");
                sb.AppendLine($"            \"{method.HttpVerb}\",");
                sb.AppendLine("            null,");
                sb.AppendLine($"            {ctVar}).ConfigureAwait(false);");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Extension methods
        var cleanInterfaceName = model.InterfaceName.StartsWith("I") && model.InterfaceName.Length > 1
            ? model.InterfaceName.Substring(1)
            : model.InterfaceName;

        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Centra.Generators\", \"1.0.0.0\")]");
        sb.AppendLine($"public static class {model.ProxyClassName}Extensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add{cleanInterfaceName}Client(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine("        string? appId = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return services.AddSingleton<{model.InterfaceName}>(sp =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var invoker = sp.GetRequiredService<global::Centra.Invocation.IServiceInvoker>();");
        sb.AppendLine($"            return new {model.ProxyClassName}(invoker, appId);");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
