<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507;NU1902;NU1903;CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="9.0.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="6.0.0" />
    <PackageVersion Include="System.ValueTuple" Version="4.5.0" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.0.3" />
    <PackageVersion Include="VaxCare.Package.Pipelining" Version="2.0.0" />
  </ItemGroup>
</Project>
