<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);NU1902;NU1903;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Package.Queueing\VaxCare.Queueing\VaxCare.Queueing.csproj" />
    <ProjectReference Include="..\..\..\Package.Queueing\VaxCare.Queueing.Core\VaxCare.Queueing.Core.csproj" />
    <ProjectReference Include="..\RabbitMQ.Benchmark.Contracts\RabbitMQ.Benchmark.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

</Project>
